import assert from 'node:assert/strict'
import { test, before, after } from 'node:test'
import { readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { chromium } from 'playwright-core'
import { build } from 'vite'
import { memoryHarness, token } from '../helpers/memory-harness.mjs'

let browser
const hub = fileURLToPath(new URL('../..', import.meta.url))
before(async () => {
  await build({ configFile: `${hub}/web/vite.config.mjs`, logLevel: 'silent' })
  browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? '/usr/bin/chromium', headless: true })
})
after(async () => { await browser?.close() })
async function pageFor(t, mode = 'ok', options = {}) {
  const h = await memoryHarness(t, mode, { web: `${hub}/web/dist`, ...options })
  const context = await browser.newContext({ viewport: { width: 1920, height: 1080 } })
  t.after(() => context.close())
  const page = await context.newPage()
  page.setDefaultTimeout(5000)
  await page.goto(`${h.base}/memory#token=${token}`)
  return { h, page }
}
test('memory graph keyboard navigation, local note preview and whole-map return', async t => {
  const { page } = await pageFor(t)
  await page.locator('.graph-node').first().waitFor()
  assert.equal(await page.locator('.graph-node').count(), 21)
  const first = page.locator('.graph-node[tabindex="0"]')
  assert.equal(await first.count(), 1)
  await first.focus()
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('Enter')
  await page.getByRole('complementary', { name: 'Note preview' }).waitFor()
  await page.getByRole('heading', { name: /Backlinks/ }).waitFor()
  await page.keyboard.press('Escape')
  await page.getByRole('complementary', { name: 'Ask your vault' }).waitFor()
  await page.goto(`${page.url().split('/memory')[0]}/memory/note/02-wiki/nestjs/bullmq-worker.md`)
  await page.getByRole('button', { name: 'Ask about this note', exact: true }).click()
  const composer = page.getByRole('textbox', { name: 'Ask your vault' })
  await composer.waitFor()
  assert.equal(await composer.inputValue(), 'About BullMQ worker (02-wiki/nestjs/bullmq-worker.md): ')
})
test('memory Ask streams a cited answer, restores the thread and keeps browser storage free of prose', async t => {
  const { page, h } = await pageFor(t)
  const question = 'Private browser question sentinel'
  await page.getByRole('textbox', { name: 'Ask your vault', exact: true }).fill(question)
  await page.getByRole('textbox', { name: 'Ask your vault', exact: true }).press('Enter')
  await page.locator('.ask-sources .citation').first().waitFor()
  assert.equal(await page.locator('.ask-sources .citation').count(), 2)
  const answer = await page.locator('.ask-answer').textContent()
  const threadUrl = page.url()
  await page.reload()
  await page.locator('.ask-answer').waitFor()
  assert.equal(page.url(), threadUrl)
  assert.equal(await page.locator('.ask-answer').textContent(), answer)
  const storage = await page.evaluate(async () => ({ local: { ...localStorage }, session: { ...sessionStorage }, databases: await indexedDB.databases(), caches: await caches.keys() }))
  assert.equal(JSON.stringify(storage).includes(question), false)
  assert.equal(JSON.stringify(storage).includes(answer), false)
  assert.ok(h.events.filter(event => event.type === 'ask.delta').every(event => event.data.ephemeral))
})
test('memory views and question palette remain available; no-graph and down states explain the failure', async t => {
  const { page } = await pageFor(t)
  await page.getByRole('tab', { name: 'Browse by MOC' }).click()
  await page.getByRole('region', { name: 'Browse by MOC' }).waitFor()
  await page.getByRole('tab', { name: /Captures/ }).click()
  await page.getByRole('region', { name: 'Captures' }).waitFor()
  const degraded = await pageFor(t, 'no-graph')
  await degraded.page.getByText(/does not provide a graph/).waitFor()
  assert.equal(await degraded.page.getByRole('complementary', { name: 'Ask your vault' }).count(), 1)
  let mode = 'exit1'
  const down = await pageFor(t, () => mode)
  await down.page.getByText('The charts are out of reach').waitFor()
  assert.match(await down.page.locator('.fail-card').textContent(), /VAULT_PATH is not a directory/)
  mode = 'ok'
  await down.page.getByRole('button', { name: 'Retry', exact: true }).click()
  await down.page.locator('.graph-node').first().waitFor()
  await down.page.getByText('Memory is back', { exact: true }).waitFor()
})
test('memory accessibility has no serious or critical axe violations', async t => {
  const { page, h } = await pageFor(t)
  await page.locator('.graph-node').first().waitFor()
  const source = await readFile(`${hub}/node_modules/axe-core/axe.min.js`, 'utf8')
  const check = async (page, surface) => {
    if (!(await page.evaluate(() => !!window.axe))) await page.evaluate(source)
    const result = await page.evaluate(() => window.axe.run(document))
    assert.deepEqual(result.violations.filter(row => ['serious', 'critical'].includes(row.impact)).map(row => ({ id: row.id, nodes: row.nodes.map(node => node.target) })), [], surface)
  }
  await check(page, 'Graph')
  for (const name of ['Browse by MOC', /Captures/, /Misses/]) { await page.getByRole('tab', { name }).click(); await check(page, String(name)) }
  await page.goto(`${h.base}/memory/note/02-wiki/nestjs/bullmq-worker.md`)
  await page.getByRole('button', { name: 'Ask about this note' }).waitFor()
  await check(page, 'Note preview')
  for (const fixture of ['answer-cited', 'answer-miss', 'general-knowledge']) {
    const answer = await pageFor(t, 'ok', { fixture, delay: '0' })
    await answer.page.getByRole('textbox', { name: 'Ask your vault' }).fill('Question for accessibility')
    await answer.page.getByRole('button', { name: 'Send', exact: true }).click()
    await answer.page.locator('.ask-answer').waitFor()
    await check(answer.page, fixture)
    await answer.page.getByRole('button', { name: 'History', exact: true }).click()
    await check(answer.page, `${fixture} History`)
  }
  const down = await pageFor(t, 'exit1')
  await down.page.getByText('The charts are out of reach').waitFor()
  await check(down.page, 'Degraded card')
  await page.goto(`${h.base}/memory`)
  await page.locator('.graph-node').first().waitFor()
  await page.keyboard.press('Alt+k')
  await page.locator('.palette-input').fill('?retry')
  await page.locator('.palette-row--askVault').waitFor()
  await check(page, 'Question palette')
})
test('memory miss and general-knowledge cards stay separate and History restores the question', async t => {
  let fixture = 'answer-miss'
  const { page } = await pageFor(t, 'ok', { fixture: () => fixture, delay: '0' })
  await page.getByRole('textbox', { name: 'Ask your vault' }).fill('Kubernetes operators?')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await page.getByText('Nothing in your vault on this.').waitFor()
  await page.getByRole('button', { name: 'History', exact: true }).click()
  assert.equal(await page.getByRole('button', { name: /Delete thread/ }).count(), 1)
  await page.getByRole('button', { name: 'New thread', exact: true }).click()
  fixture = 'general-knowledge'
  await page.getByRole('textbox', { name: 'Ask your vault' }).fill('Compose healthcheck?')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await page.getByRole('heading', { name: 'General knowledge · not from your vault' }).waitFor()
  assert.match(await page.locator('.ask-general').textContent(), /depends_on/)
  assert.doesNotMatch(await page.locator('.ask-answer').textContent(), /depends_on/)
})
test('memory Ask Stop persists cancellation and timeout restores a retryable composer (short injected timers)', async t => {
  const { page } = await pageFor(t, 'ok', { delay: '100' })
  await page.getByRole('textbox', { name: 'Ask your vault' }).fill('Slow question')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await page.getByRole('button', { name: 'Stop', exact: true }).click()
  await page.getByText('Stopped', { exact: true }).waitFor()
  const timed = await pageFor(t, 'ok', { delay: '1000', askTimers: { setTimeout: (fn, ms) => setTimeout(fn, ms >= 45000 ? 500 : ms), clearTimeout } })
  await timed.page.getByRole('textbox', { name: 'Ask your vault' }).fill('Timeout question')
  await timed.page.getByRole('button', { name: 'Send', exact: true }).click()
  await timed.page.getByText(/The ask did not finish/).waitFor()
  await timed.page.getByRole('button', { name: 'Try again', exact: true }).click()
  assert.equal(await timed.page.getByRole('textbox', { name: 'Ask your vault' }).inputValue(), 'Timeout question')
})
test('memory palette question starts a thread and Focus related citations open the note', async t => {
  const { page, h } = await pageFor(t)
  await page.locator('.graph-node').first().waitFor()
  await page.keyboard.press('Alt+k')
  await page.locator('.palette-input').fill('?how do retries work')
  await page.locator('.palette-row--askVault').waitFor()
  await page.locator('.palette-input').press('Enter')
  await page.locator('.ask-sources .citation').first().waitFor()
  assert.ok(new URL(page.url()).searchParams.get('thread'))
  const repo = '/home/you/test'
  h.deck.store.run('INSERT INTO repos(id,name,crew_slot,crew_seed,first_seen_at) VALUES(?,?,0,?,?)', repo, 'test', 'test', 1)
  h.deck.store.run("INSERT INTO sessions(id,origin,process_key,repo_id,cwd,state,state_since,since_ts,last_activity_at,alive,started_at,task) VALUES('memory-session','observed','memory-process',? ,?,'done',1,1,1,0,1,'retry backoff')", repo, repo)
  await page.goto(`${h.base}/s/memory-session?tab=memory`)
  await page.getByRole('region', { name: 'Related memory' }).waitFor()
  await page.locator('.focus-panel .citation').first().waitFor()
  await page.locator('.focus-panel .citation').first().click()
  await page.getByRole('complementary', { name: 'Note preview' }).waitFor()
  assert.match(page.url(), /\/memory\/note\//)
})
test('memory hostile note titles, tags, markdown and question text render without executable markup', async t => {
  const payloads = JSON.parse(await readFile(`${hub}/test/fixtures/ui/memory.json`, 'utf8'))
  const scenario = JSON.parse(await readFile(`${hub}/test/fixtures/vault-mcp/vault22.json`, 'utf8'))
  const worker = scenario.notes.find(note => note.path.endsWith('bullmq-worker.md'))
  worker.body = [`# ${payloads.title}`, ...payloads.body.split('\n')]
  worker.frontmatter.tags = [payloads.tag]
  const { page, h } = await pageFor(t, 'ok', { scenario })
  await page.locator('.graph-node').first().waitFor()
  assert.match(await page.locator('.graph-node').evaluateAll(nodes => nodes.map(node => node.getAttribute('aria-label')).join(' ')), /U\+202E/)
  await page.goto(`${h.base}/memory/note/${worker.path}`)
  await page.getByRole('heading', { name: /Note/ }).waitFor()
  assert.equal(await page.locator('.memory-note script, .memory-note img, .memory-note a[href^="javascript:"]').count(), 0)
  assert.match(await page.locator('.memory-note').textContent(), /U\+202E/)
  await page.goto(`${h.base}/memory?thread=new`)
  await page.getByRole('textbox', { name: 'Ask your vault' }).fill(payloads.question)
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await page.locator('.ask-sources .citation').first().waitFor()
  assert.equal(await page.locator('.ask-messages script, .ask-messages img, .ask-messages a[href^="javascript:"]').count(), 0)
  assert.match(await page.locator('.ask-message--user').textContent(), /U\+202E/)
})
